<?php $this->placeholder('menu')->set('3') ?>
<div class="well col-lg-4 col-md-offset-4">
    <h3>Добавление пользователя</h3>
<form class="form-horizontal" action="/test/add">
    <div class="form-group">
        <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" name="email" id="inputEmail" placeholder="Email">
        </div>
    </div>
    <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
            <input type="text" name="username" class="form-control" id="inputName" placeholder="name">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Добавить</button>
        </div>
    </div>
</form>
</div>


