
<?=$this->doctype('HTML5');?>
<html>

<?php  $this->headTitle('Zend') ?>
<head>
    <?php echo $this->headTitle() ?>

    <?= $this->headLink()->appendStylesheet('/bootstrap/css/bootstrap.min.css') ?>
    <?= $this->headLink()->appendStylesheet('/bootstrap/css/bootstrap-theme.min.css') ?>



    <script src="/bootstrap/js/jquery.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>

</head>
<body>
<div class="header well-sm">
    <nav class="navbar navbar-default alert alert-success">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                    <li><a href="/index/index">Главная</a></li>
                    <li><a href="/test/user">Пользователи</a></li>
                    <li><a href="/test/useradd">Добавить пользователя</a></li>
                    <li><a href="/test/index">test/index</a></li>
                    <li><a href="/test/create">Create</a></li>
                    <li><a href="/test/update">Update</a></li>
                    <li><a href="/test/get">Get</a></li>

                </ul>


            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>

    <div class="container-fluid">

<?php echo $this->layout()->content ?>
    </div>


<div class="footer well-sm">
    <nav class="navbar navbar-default alert alert-success footer-div">
    Footer
</div>
</div>

</body>
</html>
<style>
    .footer{
        position: fixed;
        bottom: 0px;
        width: 100%;

    }
    .footer-div{
        margin-bottom: 0px!important;
    }
</style>

